# Generated by Django 2.2.8 on 2021-04-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=40)),
                ('total_case', models.CharField(max_length=500)),
                ('total_death', models.CharField(max_length=500)),
                ('total_recovered', models.CharField(max_length=500)),
                ('active_case', models.CharField(max_length=500)),
                ('population', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'CovidReport',
                'verbose_name_plural': 'CovidReports',
            },
        ),
    ]
