# Generated by Django 2.2.8 on 2021-04-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19API', '0002_auto_20210411_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidreport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
